# What is an Algorithms?

An algorithm is a step-by-step procedure or method for solving a problem or accomplishing some task. In computer science, algorithms are particularly important as they form the basis for writing computer programs. Algorithms provide a clear and unambiguous description of how to perform a task, enabling efficient problem-solving and automation.

## different types of Algorithms

\begin{array}{|c|l|}
\hline
\textbf{S No.} & \textbf{Algorithms} \\
\hline 
1 & \textbf{Sorting Algorithms} \\
\hline
2 & \textbf{Searching Algorithms} \\
\hline
3 & \textbf{Greedy Algorithms} \\
\hline
4 & \textbf{Dynamic Programming} \\
\hline
5 & \textbf{Graph Algorithms} \\
\hline
6 & \textbf{Pattern Searching} \\
\hline
7 & \textbf{Recursion} \\
\hline
8 & \textbf{Backtracking} \\
\hline
9 & \textbf{Divide and Conquer} \\
\hline
10 & \textbf{Mathematical Algorithms} \\
\hline
11 & \textbf{Geometric Algorithms} \\
\hline
12 & \textbf{Bitwise Algorithms} \\
\hline
13 & \textbf{Randomized Algorithms} \\
\hline
14 & \textbf{Branch and Bound} \\
\hline
\end{array}


# 1. Sorting Algorithms

**Sorting refers to rearrangement of a given array or list of elements according to a comparison operator on the elements. The comparison operator is used to decide the new order of elements in the respective data structure.**

### Types of Sorting Techniques
There are various sorting algorithms are used in data structures. The following two types of sorting algorithms can be broadly classified:

1. **Comparison-based:** We compare the elements in a comparison-based sorting algorithm)
2. **Non-comparison-based:** We do not compare the elements in a non-comparison-based sorting algorithm)

In [2]:
from IPython.display import Image
Image(url='https://media.geeksforgeeks.org/wp-content/uploads/20220916131621/SortingTYPE.png')

**Why sorting need?** <br>
-The sorting algorithm is important in Computer Science because it reduces the complexity of a problem.

### Space Complexity & Time Complexity of different types of Sorting Algorithms

\begin{array}{|l|c|c|c|c|}
\hline
\textbf{Sorting Algorithm} & \textbf{Time Complexity - Best} & \textbf{Time Complexity - Worst} & \textbf{Time Complexity - Average} & \textbf{Space Complexity} \\
\hline
\text{Bubble Sort} & n & n^2 & n^2 & 1 \\
\hline
\text{Selection Sort} & n^2 & n^2 & n^2 & 1 \\
\hline
\text{Insertion Sort} & n & n^2 & n^2 & 1 \\
\hline
\text{Merge Sort} & n\log n & n\log n & n\log n & n \\
\hline
\text{Quicksort} & n\log n & n^2 & n\log n & \log n \\
\hline
\text{Counting Sort} & n+k & n+k & n+k & \text{max} \\
\hline
\text{Radix Sort} & n+k & n+k & n+k & \text{max} \\
\hline
\text{Bucket Sort} & n+k & n^2 & n & n+k \\
\hline
\text{Heap Sort} & n\log n & n\log n & n\log n & 1 \\
\hline
\text{Shell Sort} & n\log n & n^2 & n\log n & 1 \\
\hline
\end{array}


# I. Bubble Sort

Bubble sort is a sorting algorithm that compares two adjacent elements and swaps them until they are in the intended order.

Just like the movement of air bubbles in the water that rise up to the surface, each element of the array move to the end in each iteration. Therefore, it is called a bubble sort. <br>
**Working of Bubble Sort**<br>
Suppose we are trying to sort the elements in ascending order.

**1. First Iteration (Compare and Swap)**

1. Starting from the first index, compare the first and the second elements.
2. If the first element is greater than the second element, they are swapped.
3. Now, compare the second and the third elements. Swap them if they are not in order.
4. The above process goes on until the last element.


In [3]:
Image(url='https://www.programiz.com/sites/tutorial2program/files/Bubble-sort-0.png')

**2. Remaining Iteration**

The same process goes on for the remaining iterations.

After each iteration, the largest element among the unsorted elements is placed at the end.

In [4]:
Image(url='https://www.programiz.com/sites/tutorial2program/files/Bubble-sort-1.png')

In [5]:
Image(url='https://www.programiz.com/sites/tutorial2program/files/Bubble-sort-2.png')

In [6]:
Image(url='https://www.programiz.com/sites/tutorial2program/files/Bubble-sort-3.png')

### Bubble Sort Algorithm

In [7]:
from numpy import array

In [8]:
def bubble_sort(arr):
    for r in range(1,len(arr)):
        for i in range (len(arr)-r):
            if arr[i]>arr[i+1]:
                arr[i],arr[i+1]=arr[i+1],arr[i]
                
l=array([34,64,3,5,6,78,4])
print('unsorted array:',l)
bubble_sort(l)
print('sorted array:',l)

unsorted array: [34 64  3  5  6 78  4]
sorted array: [ 3  4  5  6 34 64 78]


In [9]:
def Bubble_Sort(arr):
    for r in range(1,len(arr)):
        print(f'step: {r}')
        for i in range (len(arr)-r):
            if arr[i]>arr[i+1]:
                arr[i],arr[i+1]=arr[i+1],arr[i]
                print(arr)
            else:
                print(arr)
        print()
            
A=array([13,64,33,35,26,78,4])

Bubble_Sort(A)
print('sorted array:',A)

step: 1
[13 64 33 35 26 78  4]
[13 33 64 35 26 78  4]
[13 33 35 64 26 78  4]
[13 33 35 26 64 78  4]
[13 33 35 26 64 78  4]
[13 33 35 26 64  4 78]

step: 2
[13 33 35 26 64  4 78]
[13 33 35 26 64  4 78]
[13 33 26 35 64  4 78]
[13 33 26 35 64  4 78]
[13 33 26 35  4 64 78]

step: 3
[13 33 26 35  4 64 78]
[13 26 33 35  4 64 78]
[13 26 33 35  4 64 78]
[13 26 33  4 35 64 78]

step: 4
[13 26 33  4 35 64 78]
[13 26 33  4 35 64 78]
[13 26  4 33 35 64 78]

step: 5
[13 26  4 33 35 64 78]
[13  4 26 33 35 64 78]

step: 6
[ 4 13 26 33 35 64 78]

sorted array: [ 4 13 26 33 35 64 78]


In [14]:
def bubblesort(arr):
    size= len(arr)
    for k in range(size-1):
        for i in range(size-1):
            if arr[i]>arr[i+1]:
                arr[i],arr[i+1]=arr[i+1],arr[i]

A=array([544,32,32,12,243,453])
bubblesort(A)
A

array([ 12,  32,  32, 243, 453, 544])

**Optimized Bubble Sort Algorithm**

In the above algorithm, all the comparisons are made even if the array is already sorted.

This increases the execution time.

To solve this, we can introduce an extra variable swapped. The value of swapped is set true if there occurs swapping of elements. Otherwise, it is set false.

After an iteration, if there is no swapping, the value of swapped will be false. This means elements are already sorted and there is no need to perform further iterations.

This will reduce the execution time and helps to optimize the bubble sort.

### Algorithm for optimized bubble sort

In [16]:
def bubblesort(arr):
    size= len(arr)
    for k in range(size-1):
        swapped=False
        for i in range(size-1):
            if arr[i]>arr[i+1]:
                arr[i],arr[i+1]=arr[i+1],arr[i]
                swapped=True
        if not swapped:
            break

A=array([544,32,32,12,243,453])
bubblesort(A)
A        

array([ 12,  32,  32, 243, 453, 544])

# II. Selection Sort 

Selection sort is a sorting algorithm that selects the smallest element from an unsorted list in each iteration and places that element at the beginning of the unsorted list.

In [18]:
Image(url='https://miro.medium.com/v2/resize:fit:750/format:webp/0*pK2-pSUoAnIR_Eg7.png')

In [29]:
def selection_sort(arr):
    size=len(arr)
    for i in range(size-1):
        min_index=i
        for j in range(min_index+1,size):
            if arr[j]<arr[min_index]:
                min_index= j
        if i!=min_index:
            arr[i],arr[min_index]=arr[min_index],arr[i]
            
A=array([34,5,7,12,34,34,12,1])
selection_sort(A)
print(A)

[ 1  5  7 12 12 34 34 34]
